### ISSUE TITLE
Missing the way to trigger a class' associated test upon save.

### ISSUE THREAD

**Issue by Dalamar** [colby-swandale/guard-codeception#7]
If following a TDD cycle, we are surely need a way to trigger a class' associated test upon save.
Expecting following configuration in Guardfile would trigger only tests/MyClassTest.php upon saving the file application/MyClass.php:

```
guard :codeception, :codecept => 'vendor/bin/codecept' do
  watch(%r{application/(.+).php}) { |m| "tests/#{m[1]}Test.php" }
end
```

Currently guard fires all the tests upon saving any of files in application dir.

Please implement this feature if you can.

**Comment by colby-swandale** [comment]
Apologies, this project is no longer being maintained.
